name: Daethyra's Workflow

# Author: Daethyra (Daemon Carino)

# Triggers
on:
  push:
    branches:
      - main
      # Uncomment and add other branches to run the workflow on
      # - working/*
  pull_request:
    branches:
      - main
      # Uncomment and add other branches to run the workflow on
      # - working/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    # Robust caching for pip
    - name: Cache pip dependencies
      uses: actions/cache@v3.2.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: pytest
    
    # Linting step
    - name: Install pylint
      run: pip install pylint
    
    - name: Run pylint
      run: pylint $(git ls-files '*.py')

  handle-stale:
    runs-on: ubuntu-latest
    steps:
    - name: Mark and close stale issues and PRs
      uses: actions/stale@v6.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 3
        days-before-close: 7
